;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;Assembly Equivalent Of BOOT12.BIN                                           ;
;Converted By MiniTAK BIN2ASM Version 0.1 , 2005                             ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        RAW_DATA                LABEL                   BYTE
                DB       0EBH, 3CH, 90H, 4DH, 53H, 44H, 4FH, 53H, 35H, 2EH
                DB        30H, 00H, 02H, 01H, 01H, 00H, 02H,0E0H, 00H, 40H
                DB        0BH,0F0H, 09H, 00H, 12H, 00H, 02H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 29H,0EAH
                DB        18H, 44H, 40H, 4DH, 49H, 4EH, 49H, 54H, 41H, 4BH
                DB        5FH, 4FH, 53H, 20H, 46H, 41H, 54H, 31H, 32H, 20H
                DB        20H, 20H, 31H,0C0H, 8EH,0D8H, 8EH,0D0H,0BCH, 00H
                DB        7CH, 89H,0E5H, 88H, 56H, 24H, 8AH, 46H, 10H,0F7H
                DB        66H, 16H, 03H, 46H, 0EH, 8BH, 76H, 11H,0B1H, 04H
                DB        4EH,0D3H,0EEH, 46H,0BFH, 03H, 00H,0E8H, 8CH, 00H
                DB        50H, 8BH, 56H, 11H, 1EH, 07H,0BFH, 00H, 06H, 4AH
                DB        78H, 6AH,0BEH,0F3H, 7DH,0B9H, 0BH, 00H, 8DH, 45H
                DB        20H, 50H,0F3H,0A6H, 5FH, 75H,0EEH,0FFH, 75H,0FAH
                DB        8BH, 46H, 0EH, 8BH, 76H, 16H,0BFH, 03H, 00H,0E8H
                DB        62H, 00H, 5BH, 89H,0DEH, 89H,0D8H, 81H,0FBH,0F8H
                DB        0FH, 73H, 1AH, 40H, 89H,0DFH,0D1H,0DBH, 8BH, 99H
                DB        00H, 86H, 73H, 08H,0D1H,0EBH,0D1H,0EBH,0D1H,0EBH
                DB       0D1H,0EBH, 80H,0E7H, 0FH, 39H,0D8H, 74H,0E0H, 29H
                DB       0F0H, 74H, 1EH, 53H, 8AH, 5EH, 0DH,0B7H, 00H,0F7H
                DB       0E3H,0BFH, 80H, 00H, 01H, 06H,0C0H, 7CH, 96H, 48H
                DB        48H,0F7H,0E3H, 03H, 46H,0FEH, 10H,0F2H,0E8H, 1FH
                DB        00H,0EBH,0B9H,0EAH, 00H, 00H, 00H, 10H,0BEH, 48H
                DB        7DH,0B8H, 0DH, 0EH,0BBH, 07H, 00H,0CDH, 10H,0ACH
                DB        84H,0C0H, 75H,0F9H, 30H,0E4H,0CDH, 16H,0CDH, 19H
                DB        31H,0D2H, 52H, 50H, 03H, 46H, 1CH, 13H, 56H, 1EH
                DB        8BH, 5EH, 18H,0F7H,0F3H, 29H,0D3H, 39H,0F3H, 76H
                DB        02H, 89H,0F3H, 42H, 89H,0D1H, 99H,0F7H, 76H, 1AH
                DB        88H,0D6H, 86H,0E8H,0D0H,0CCH,0D0H,0CCH, 00H,0E1H
                DB        29H,0F8H, 83H,0E0H, 7FH, 74H, 04H, 39H,0D8H, 76H
                DB        01H, 93H, 50H, 89H,0FBH, 51H,0B1H, 05H,0D3H,0E3H
                DB        59H, 8EH,0C3H, 31H,0DBH, 8AH, 56H, 24H,0B4H, 02H
                DB       0CDH, 13H, 72H,0A0H, 5BH, 58H, 5AH, 01H,0D8H, 10H
                DB       0F2H, 01H,0DFH, 29H,0DEH, 75H,0ABH,0C3H, 0AH, 45H
                DB        72H, 72H, 6FH, 72H, 3AH, 20H, 55H, 6EH, 61H, 62H
                DB        6CH, 65H, 20H, 74H, 6FH, 20H, 66H, 69H, 6EH, 64H
                DB        20H, 4DH, 49H, 4EH, 49H, 49H, 4FH, 2EH, 53H, 59H
                DB        53H, 0DH, 0AH, 50H, 72H, 65H, 73H, 73H, 20H, 61H
                DB        6EH, 79H, 20H, 6BH, 65H, 79H, 20H, 74H, 6FH, 20H
                DB        72H, 65H, 62H, 6FH, 6FH, 74H, 0DH, 0AH, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
                DB        00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 4DH
                DB        49H, 4EH, 49H, 49H, 4FH, 20H, 20H, 53H, 59H, 53H
                DB        55H,0AAH